Release/v0.7.8
reflex-media/lesgo-framework pull request #73
Opened 2022-06-17 05:24 UTC by inonbaguio

2022-06-30 05:13 UTC, daison12006013 commented
@inonbaguio Kindly re-run the CI above? it looks like it get stuck?

2022-06-30 06:48 UTC, daison12006013 submitted a review, later dismissed
LGTM!

2022-07-11 03:05 UTC, xXLXx requested changes
@jpaylaga we can remove serverAuthMiddleware instead as we can stack middlewares anyways

2022-12-06 01:21 UTC, mosufy approved these changes

2022-12-06 01:24 UTC, merged